import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavSidebar from "@/components/NavSidebar/NavSidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { Suspense } from "react";
import { RouteChangeListener } from "@/components/RouteChangeListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <Suspense fallback={<div>Loading RouteChangeListener...</div>}>
            <RouteChangeListener />
          </Suspense>
          <NavSidebar />

          <Suspense>
            <SidebarInset className="overflow-hidden">{children}</SidebarInset>
          </Suspense>
        </SidebarProvider>
      </body>
    </html>
  );
}
